---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: attendee-service-source

run:
  path: attendee-service-source/ci/tasks/update-routes.sh
