---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/sathyarajan/pcf-attendee-service-code  #<---- REPLACE ME
    branch: bluegreen_branch

- name: deploy-attendee-service
  type: cf
  source:
    api: api.system.dev.digifabricpcf.com        #<---- REPLACE ME
    username: {{cf-user}}
    password: {{cf-password}}
    organization: sneethirajan-pal    #<---- REPLACE ME
    space: SpaceDeveloper         #<---- REPLACE ME
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy_blue_green
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest-blue-green.yml
      path: package-output/attendee-service.jar

- name: smoke_test_blue_green
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy_blue_green]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://attendee-service-green.app.dev.digifabricpcf.com

- name: bind_green_canonical
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [smoke_test_blue_green]   
  - task: bing_green_canonical
    file: attendee-service-source/ci/tasks/update-routes.yml
    params:  
      PWS_API: api.system.dev.digifabricpcf.com
      PWS_ORG: sneethirajan-pal
      PWS_USER: {{cf-user}}
      PWS_PWD: {{cf-password}}
      PWS_SPACE: SpaceDeveloper

- name: smoke_test_green_canonical
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [bind_green_canonical]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://attendee-service-public.app.dev.digifabricpcf.com
